<a href="https://colab.research.google.com/github/Manishjr18/parul/blob/master/HPC_LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import statistics as st

In [ ]:
age = [20,19,20,18,21,22]
m_age = st.mean(age)
print('Mean Age :', m_age)

Mean Age : 20


In [ ]:
age = [20,19,20,18,21,22]
v_age = st.variance(age)
print('Variance age :',v_age)

Variance age : 2


In [ ]:
#installing numpy
!pip install numpy

In [ ]:
#importing numpy
import numpy as np

In [ ]:
a1 = np.array(20)
print(a1)
print('Dim',a1.ndim)

20
Dim 0


In [ ]:
a2 = np.array([10,20,30,10,30,405,505,50,50])
print(a2)
print('Dim',a2.ndim)

[ 10  20  30  10  30 405 505  50  50]
Dim 1


In [ ]:
a3 = np.array([[10,20,30],[10,30,405],[505,50,50]])
print(a3)
print('Dim',a3.ndim)

[[ 10  20  30]
 [ 10  30 405]
 [505  50  50]]
Dim 2


In [ ]:
a3 = np.array([[10,20,30],[10,30,405],[505,50,50]],dtype=np.int16)

print(a3)
print('Dim',a3.ndim)
print('shape :',a3.shape)
print('size :',a3.size)
print('Item Size :',a3.itemsize)
print('Data type :',a3.dtype)


[[ 10  20  30]
 [ 10  30 405]
 [505  50  50]]
Dim 2
shape : (3, 3)
size : 9
Item Size : 2
Data type : int16


In [ ]:
a11 = np.empty((5,5))
a11

array([[4.97393427e-310, 0.00000000e+000, 6.61302520e-310,
        6.61302520e-310, 6.61302523e-310],
       [6.61302520e-310, 6.61302520e-310, 6.61302520e-310,
        6.61302520e-310, 6.61302520e-310],
       [6.61302520e-310, 6.61302520e-310, 6.61302520e-310,
        6.61302520e-310, 6.61302520e-310],
       [6.61302520e-310, 6.61302520e-310, 6.61302520e-310,
        6.61302520e-310, 6.61302520e-310],
       [6.61302520e-310, 6.61302520e-310, 6.61302520e-310,
        6.61302520e-310, 1.66006057e-321]])

In [ ]:
a12 = np.zeros((3,5))
a12

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a14 = np.arange(2,101,2)
a14

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
a15 = np.reshape(a14, (10,5))
a15

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [ ]:
a14 = np.reshape(a14,(2,5,5))
a14

array([[[  2,   4,   6,   8,  10],
        [ 12,  14,  16,  18,  20],
        [ 22,  24,  26,  28,  30],
        [ 32,  34,  36,  38,  40],
        [ 42,  44,  46,  48,  50]],

       [[ 52,  54,  56,  58,  60],
        [ 62,  64,  66,  68,  70],
        [ 72,  74,  76,  78,  80],
        [ 82,  84,  86,  88,  90],
        [ 92,  94,  96,  98, 100]]])

In [ ]:
a1 = np.arange(10,100,10)
a1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print('1st ele :', a1[0])

1st ele : 10


In [ ]:
print('5th ele :', a1[4])

5th ele : 50


In [ ]:
print('last ele :', a1[-1])

last ele : 90


In [ ]:
print('2nd ele from rev end :', a1[-2])

2nd ele from rev end : 80


In [ ]:
print('1st 5 ele :', a1[:5])

1st 5 ele : [10 20 30 40 50]


In [ ]:
print('last 5 ele :', a1[-5:])

last 5 ele : [50 60 70 80 90]


In [ ]:
print('alternate ele :', a1[::2])

alternate ele : [10 30 50 70 90]


In [ ]:
a12 = np.arange(1,101)
a12 = np.reshape(a12,(10,10))
a12

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
print('ele at 1st row 1st column :', a12[0][0])

ele at 1st row 1st column : 1


In [ ]:
print('ele at 1st row 5tt column :', a12[0,4])

ele at 1st row 5tt column : 5


In [ ]:
print('ele at 2nd row :', a12[1])

ele at 2nd row : [11 12 13 14 15 16 17 18 19 20]


In [ ]:
print('1st and last row values')
print(a12[[0,-1],:])


1st and last row values
[[  1   2   3   4   5   6   7   8   9  10]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
print('1st and 3rd row values')
print(a12[[0,2],:])

1st and 3rd row values
[[ 1  2  3  4  5  6  7  8  9 10]
 [21 22 23 24 25 26 27 28 29 30]]


In [ ]:
#installing panda
!pip install pandas

In [ ]:
#importing panda
import pandas as pd

In [ ]:
prod_dict = {
    'pid': [10,20,30,40],
    'pname':['iphone','Galaxy','Narzo','Lumia'],
    'price':[85000,60000,25000,15000],
    'vendor':['Apple','Samsung','Realme','Nokia']
}
prod_dict

{'pid': [10, 20, 30, 40],
 'pname': ['iphone', 'Galaxy', 'Narzo', 'Lumia'],
 'price': [85000, 60000, 25000, 15000],
 'vendor': ['Apple', 'Samsung', 'Realme', 'Nokia']}

In [ ]:
prod_df = pd.DataFrame(prod_dict)
prod_df

pid   pname  price   vendor
0   10  iphone  85000    Apple
1   20  Galaxy  60000  Samsung
2   30   Narzo  25000   Realme
3   40   Lumia  15000    Nokia

In [ ]:
prod_df.size

16

In [ ]:
prod_df.shape

(4, 4)

In [ ]:
prod_df.dtypes

pid        int64
pname     object
price      int64
vendor    object
dtype: object

In [ ]:
prod_df.values

array([[10, 'iphone', 85000, 'Apple'],
       [20, 'Galaxy', 60000, 'Samsung'],
       [30, 'Narzo', 25000, 'Realme'],
       [40, 'Lumia', 15000, 'Nokia']], dtype=object)

In [ ]:
prod_df.columns

Index(['pid', 'pname', 'price', 'vendor'], dtype='object')

In [ ]:
prod_df.index

RangeIndex(start=0, stop=4, step=1)

In [1]:
number = 5
squared = number ** 2
squared


25

In [2]:
print("Welcome HPC")

Welcome HPC
